name: EnderEye-TP
main: TP\Main
version: 1.0
api: [1.3.1]
load: POSTWORLD
author: jasonwynn10 & TylerGames
commands:
    wild:
        description: teleports player to a random location in the world
        usage: "/wild"
	permission: wild.command

permissions:
    wild.cmd:
        description: "Allows access to wild features"
	default: true
	children:
		wild.command:
			description: "teleports player to a random location in the world"
			default: true
			
